### ISSUE TITLE
Pass Site_of_care to ReportStream

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#2040]
### Description
Send the organization type to ReportStream as `Site_of_care`. This is part of the AoE requirements, that we haven't been providing.

### Additional context
- `Site_of_care` was requested by FL PHD
- Here's the list of possible values for Site_of_care. Pretty sure we do not need all of these initially:
```
    name: site_of_care
    system: SNOMED_CT
    referenceUrl: https://www.hhs.gov/sites/default/files/hhs-guidance-implementation.pdf
    values:
    - display: Hospital
    code: 22232009
    - display: Long Term Care Hospital
    code: 32074000
    - display: Secure Hospital
    code: 224929004
    - display: Nursing Home
    code: 42665001
    - display: Retirement Home
    code: 30629002
    - display: Orphanage
    code: 74056004
    - display: Prison-based care site
    code: 722173008
    - display: Substance Abuse Treatment Center
    code: 20078004
    - display: Boarding House
    code: 257573002
    - display: Military Accommodation
    code: 224683003
    - display: Hospice
    code: 284546000
    - display: Hostel
    code: 257628001
    - display: Sheltered Housing
    code: 310207003
    - display: Penal Institution
    code: 57656006
    - display: Homeless
    code: 32911000
```
