### ISSUE TITLE
Remove `device_test_performed_loinc_code` table

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#5466]
### Background
As part of the change to add `test_ordered_loinc` to device, the table `device_test_performed_loinc_code` has been renamed. In order to complete that, a new table with the same data had to have been created. 

### Action requested
Drop the `device_test_performed_loinc_code` table, if the drop fails the roll back should recreate the table with this schema
```
        - createTable:
            tableName: device_test_performed_loinc_code
            columns:
              - column:
                  name: internal_id
                  type: uuid
                  remarks: The internal database identifier for this entity.
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: device_type_id
                  remarks: The reference to the device type.
                  type: uuid
                  constraints:
                    nullable: false
                    foreignKeyName: fk__device_supported_disease__device_type
                    references: device_type
              - column:
                  name: supported_disease_id
                  remarks: The reference to the supported disease.
                  type: uuid
                  constraints:
                    nullable: false
                    foreignKeyName: fk__device_supported_disease__supported_disease_type
                    references: supported_disease
              - column:
                  name: test_performed_loinc_code
                  remarks: The code that identifies which disease was tested.
                  type: text
                  constraints:
                    nullable: false
              - column:
                  name: equipment_uid
                  remarks: represents the data from "Equipment UID" column in the LIVD
                  type: text
              - column:
                  name: testkit_name_id
                  remarks: represents the data from "Testkit Name ID" column in the LIVD
                  type: text
```

### Acceptance Criteria
`device_test_performed_loinc_code` no longer exists
